yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


app_name = 'posts'

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название',
        help_text='Введите название группы',
        max_length=200
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Опишите название группы'
    )
    slug = models.SlugField(
        verbose_name='Человекочитаемый ID',
        unique=True
    )

    def __str__(self):
        return self.title


class Post(models.Model):

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):

    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'name': "text",
                    'cols': "40",
                    'rows': "10",
                    'class': "form-control",
                    'id': "id_text"
                }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'name': "text",
                    'cols': "40",
                    'rows': "2",
                    'class': "form-control",
                    'id': "id_text"
                }
            ),
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.cache import cache_page
from .models import Follow, Post, Group, User
from .forms import PostForm, CommentForm
User = get_user_model()


@cache_page(20)
def index(request):
    """Главная страница."""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница группы."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Страница пользователя."""
    author = get_object_or_404(User, username=username)
    profile_post = author.posts.all()
    paginator = Paginator(profile_post, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user.id, author=author).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница поста."""
    post = get_object_or_404(Post, pk=post_id)
    comment = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comment,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        post.save()
        return redirect('posts:post_detail', post.pk)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_create(request):
    """создание поста."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Добавление комментария."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Страница постов на которые подписан."""
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author and not Follow.objects.filter(
            user=request.user, author=author).exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = get_object_or_404(User, username=username)
    unfollow = Follow.objects.filter(user=request.user, author=author)
    if unfollow.exists():
        unfollow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>
        © {{ year }} Copyright <span style="color:red">Ya</span>tube
    </p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img width="30" height="30" class="d-inline-block align-top" alt="" src="{% static 'img/logo.png' %}">
                <span style="color:red">Ya</span>tube
            </a>
            <ul class="nav  nav-pills">
                <li class="nav-item">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name  == 'about:author' %}
                    active{% endif %}" href="{% url 'about:author' %}">
                        Об авторе
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name  == 'about:tech' %}
                    active{% endif %}" href="{% url 'about:tech' %}">
                        Технологии
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name  == 'posts:post_create' %}
                    active{% endif %}" href="{% url 'posts:post_create' %}">
                        Новая запись
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="<!--  -->">Изменить пароль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
                </li>
                <li>
                    Пользователь: {{ user.username }}
                <li>
                    {% else %}
                <li class="nav-item">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name  == 'users:login' %}
                    active{% endif %}" href="{% url 'users:login' %}">
                        Войти
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link 
                    {% if request.resolver_match.view_name  == 'users:signup' %}
                    active{% endif %}" href="{% url 'users:signup' %}">
                        Регистрация
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
            </a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active">
            <span class="page-link">{{ i }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

yatube/templates/includes/post.html
{% load thumbnail %}
<ul>
    <li>
        Автор:
        {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
        </a>
    </li>
    <li>
        Дата публикации:
        {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>
    {{ post.text|linebreaks }}
</p>
<p>
    <a href="{% url 'posts:post_detail' post.pk %}">
        Детали поста
    </a>
</p>
{% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}">
    Все записи группы "{{ post.group.title }}"
</a>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
<div class="row my-3">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}