yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


app_name = 'posts'

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название',
        help_text='Введите название группы',
        max_length=200
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Опишите название группы'
    )
    slug = models.SlugField(
        verbose_name='Человекочитаемый ID',
        unique=True
    )

    def __str__(self):
        return self.title


class Post(models.Model):

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):

    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'name': "text",
                    'cols': "40",
                    'rows': "10",
                    'class': "form-control",
                    'id': "id_text"
                }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'name': "text",
                    'cols': "40",
                    'rows': "2",
                    'class': "form-control",
                    'id': "id_text"
                }
            ),
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.cache import cache_page
from .models import Follow, Post, Group, User
from .forms import PostForm, CommentForm
User = get_user_model()


@cache_page(20)
def index(request):
    """Главная страница."""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница группы."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Страница пользователя."""
    author = get_object_or_404(User, username=username)
    profile_post = author.posts.all()
    paginator = Paginator(profile_post, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user.id, author=author).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница поста."""
    post = get_object_or_404(Post, pk=post_id)
    comment = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comment,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        post.save()
        return redirect('posts:post_detail', post.pk)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_create(request):
    """создание поста."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Добавление комментария."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Страница постов на которые подписан."""
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author and not Follow.objects.filter(
            user=request.user, author=author).exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = get_object_or_404(User, username=username)
    unfollow = Follow.objects.filter(user=request.user, author=author)
    if unfollow.exists():
        unfollow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактирование поста
{% else %}
Создание нового поста
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}
                    Редактировать пост
                    {% else %}
                    Новый пост
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" {% if is_edit %} action="{% url 'posts:post_edit' post.id %}" {% else %}
                        action="{% url 'posts:post_create' %}" {% endif %} enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
                            aria-required="false" {% endif %}>
                            <label for="{{ field.id_for_label }}">
                                {{ field.label|safe }}
                                {% if field.field.required %}
                                <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            <div>
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                    Сохранить
                                    {% else %}
                                    Добавить
                                    {% endif %}
                                </button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
<h1>
    Последние обновления на сайте
</h1>
{% include 'includes/switcher.html' %}
{% for post in page_obj %}
{% include 'includes/post.html' %}
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
{{ group.title }}
{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>{{ group.description }}</p>
{% for post in page_obj %}
{% include 'includes/post.html' %}
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
<h1>
    Последние обновления на сайте
</h1>
{% for post in page_obj %}
<ul>
    <li>
        Автор:
        {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
        </a>
    </li>
    <li>
        Дата публикации:
        {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
<p>
    {{ post.text|linebreaks }}
</p>
<p>
    <a href="{% url 'posts:post_detail' post.pk %}">
        Детали поста
    </a>
</p>
{% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}">
    Все записи группы "{{ post.group.title }}"
</a>
{% endif %}
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
Пост:
{{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
<div class="row">
    <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Дата публикации:
                {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
                Группа:
                {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                    Все записи группы
                </a>
            </li>
            {% endif %}
            <li class="list-group-item">
                Автор:
                {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:
                <span>
                    {{ post.author.posts.count }}
                </span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                    все посты пользователя
                </a>
            </li>
        </ul>
    </aside>
    <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text|linebreaks }}
        </p>
        {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}
                    <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
        {% endif %}
        {% for comment in comments %}
        <div class="media mb-4">
            <div class="media-body">
                <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                    </a>
                </h5>
                <p>
                    {{ comment.text }}
                </p>
            </div>
        </div>
        {% endfor %}
        {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            Редактировать запись
        </a>
        {% endif %}
    </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профайл пользователя
{{ author }}
{% endblock %}
{% block content %}
<div class="container py-5">
    <h1>Все посты пользователя
        {{ author.get_full_name }}
    </h1>
    <h3>Всего постов:
        {{ page_obj.paginator.count }}
    </h3>
    {% if following %}
    <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author %}" role="button">
        Отписаться
    </a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author %}" role="button">
        Подписаться
    </a>
    {% endif %}
    <article>
        {% for post in page_obj %}
        {% include 'includes/post.html' %}
        {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
    </article>
</div>
{% include 'includes/paginator.html' %}
{% endblock %}